services:
  backend:
    build: ./backend
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${SECRET_KEY:-default_secret_key}
      - DEBUG=True
  frontend:
    build: ./frontend
    command: npm run start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
